spring:
  datasource:
    url: jdbc:mysql://containers-us-west-64.railway.app:5458/railway
    username: root
    password: l93E2lQLcHI7vrCv6pbv
    name: femfy_db

#  sql:
#    init:
#     mode: always # you won't do this in prod, I'm just doing this for demo purposes